#!/usr/bin/env bash
#Secuencia de comandos Bash que muestra "Bset School" 10 veces, pero para la novena línea muestra "Best School" y luego "Hi" en una nueva línea
counter=0
while [ $counter -lt 11 ]
do
if [ $counter = 9 ]
then
echo "Hi"
fi
echo "Best School"
let counter+=1
done
