#!/usr/bin/env bash
#Secuencia de comandos Bash que muestra "Bset School" 10 veces, pero para la novena línea muestra "Best School" y luego "Hi" en una nueva línea
COUNTER=0
while [ $COUNTER -lt 11 ]
do
if [ $COUNTER = 9 ]
then
echo "Hi"
else
echo "Best School"
fi
let COUNTER+=1
done
